Connect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from users.middlewares.auth import LogoutCheckMiddleware
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('users.urls')),
    path("", include('market.urls')),
    path("login/", LogoutCheckMiddleware(auth_view.LoginView.as_view(template_name="users/login.html")), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'market.views.error_404'
handler500 = 'market.views.error_500'

market/urls.py
from django.urls import path, re_path
from . import views as market_view


urlpatterns = [
    path("", market_view.home, name="home"),
    path("market/", market_view.market_view, name="market"),
    path("paginate_products/", market_view.paginate_products, name="paginate_products"),
    path("high_low_price_products/", market_view.high_low_price_products, name="high_low_price_products"),
    path("recent_products/", market_view.recent_products, name="recent_products"),
    path("product/<uuid:pk>/", market_view.product_detail, name="product-detail"),
    path("<uuid:pk>/add_to_checkout/", market_view.add_to_checkout, name="add_to_checkout"),
    path("<uuid:pk>/remove_from_checkout/", market_view.remove_from_checkout, name="remove_from_checkout"),
    path("<uuid:pk>/delete_from_checkout/", market_view.delete_from_checkout, name="delete_from_checkout"),
    path("checkout/", market_view.checkout, name="checkout"),
    path("process_order/", market_view.process_order, name="process_order"),
    path("product/<uuid:pk>/update/", market_view.ProductUpdate.as_view(), name="product-update"),
    path("product/<uuid:pk>/review/", market_view.product_review, name="productReview"),
    path("create/", market_view.create_view, name="create"),
    path("search/", market_view.search, name="search"),
    path("about/", market_view.about, name="about"),

]

users/urls.py
from django.urls import path
from . import views as user_view
from users.middlewares.auth import LogoutCheckMiddleware

urlpatterns = [
    path("register/", LogoutCheckMiddleware(user_view.register), name="register"),
    path("vendor/<str:username>/", user_view.vendor_view, name="vendor"),
    path("dashboard/", user_view.vendor_dashboard, name="vendor_dashboard"),
    path('update-profile/', user_view.update_profile, name='update_profile'),
    path("notification/", user_view.notification_view, name="notification"),
    path("create-store/", user_view.create_store, name="create_store"),
    path("<str:username>/follow", user_view.UserFollowerApi.as_view(), name="follower_vendor"),
    path('api/<str:username>/post_notify/', user_view.PostNotificationApi.as_view(), name='post_notify'),
    path('mark_as_read/', user_view.mark_as_read, name='update_notification'),
    path('settings/', user_view.settings, name='settings'),
    path('ajax/paginate/', user_view.paginate, name='paginate'),
    path('delete_account/<str:username>/', user_view.delete_account, name='delete_account'),
    path('export_products/', user_view.export_products, name='export_products'),
    path('request_withdrawal/', user_view.request_withdrawal, name='request_withdrawal'),
    path('ajax_all_order/', user_view.ajax_all_order, name='ajax_all_order'),

    path('ajax/validate_username/', user_view.validate_username, name='validate_username'),

]

market/models.py
import secrets
from statistics import mean

from django.db import models
from django.conf import settings
from datetime import datetime, date
from django.shortcuts import reverse
import uuid
from .paystack import Paystack
from ckeditor.fields import RichTextField
# from djrichtextfield.models import RichTextField


# Create your models here.


class Vendor(models.Model):
    EDUCATION_TYPES = (
        (1, "B.Sc."), (2, "M.Sc."), (3, "M.A."), (4, "M.Sc."), (5, "LLB"), (6, "Others"),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, default="")
    phone_number = models.CharField(max_length=11, null=True, blank=True)
    about = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(default='profile_picture/download_EPBN0x6.jpg', upload_to='profile_picture')
    education = models.IntegerField(choices=EDUCATION_TYPES, default=6)
    follower = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='vendor_follower_list')
    following = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='vendor_following_list')
    account_visit = models.IntegerField(default=0)
    account_engaged = models.IntegerField(default=0)
    is_verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=datetime.now)
    twitter_url = models.URLField(default="")
    instagram_url = models.URLField(default="")
    skills = models.CharField(max_length=20, default="")
    total_earnings = models.FloatField(default=0)
    current_balance = models.FloatField(default=0)
    withdrawal_pin = models.CharField(max_length=4, default="")
    paid_until = models.DateField(
        null=True,
        blank=True
    )

    def set_paid_until(self, date_or_timestamp):
        if isinstance(date_or_timestamp, int):
            # input date as timestamp integer
            paid_until = date.fromtimestamp(date_or_timestamp)
        elif isinstance(date_or_timestamp, str):
            # input date as timestamp string
            paid_until = date.fromtimestamp(int(date_or_timestamp))
        else:
            paid_until = date_or_timestamp

        self.paid_until = paid_until
        self.save()

    def has_paid(
            self,
            current_date=datetime.now()
    ):
        if self.paid_until is None:
            return False

        return current_date < self.paid_until

    def __str__(self):
        return f"{self.user}"


class VendorReview(models.Model):
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    date_posted = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return f"{self.sender}"


class Category(models.Model):
    name = models.CharField(max_length=100, default="Select Category")
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name

    @staticmethod
    def getAllCategory():
        return Category.objects.all()


class Product(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    image = models.ImageField(default='2placeholder_test_b9l9NT5.png', upload_to='product_images')
    description = RichTextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_purchase = models.IntegerField(default=0)
    rating_count = models.FloatField(default=0)
    shipping_fee = models.FloatField(default=10)
    vendor = models.ForeignKey(Vendor, null=True, blank=True, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=datetime.now)
    date_updated = models.DateTimeField(auto_now=True)
    delivery_period = models.IntegerField(default=0)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product-detail", kwargs={"pk": self.id})

    @staticmethod
    def getProductByFilter(category_id):
        if category_id:
            return Product.objects.filter(category=category_id)
        else:
            return Product.objects.all()

    def amount(self):
        total = self.price * self.product_purchase
        return total


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(default='2placeholder_test_b9l9NT5.png', upload_to='product_images')
    date_posted = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"{self.image}"


class Checkout(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    complete = models.BooleanField(default=False, null=True, blank=True)
    date_posted = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return f'{self.user}: {self.quantity} of {self.product}'

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=30)
    order_item = models.ManyToManyField(Checkout, related_name="order_item")
    default_order_item = models.CharField(max_length=1000, null=True, blank=True)
    default_price = models.FloatField(default=0)
    vendor = models.ForeignKey(Vendor, blank=True, null=True, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    date_posted = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return f'{self.user}'

    @property
    def total_order_item_price(self):
        total = self.order_item.all()
        total_price = sum([i.get_total for i in total])
        return total_price


class ProductReview(models.Model):
    RATING_TYPES = (
        (1, "★☆☆☆☆ (1/5)"), (2, "★★☆☆☆ (2/5)"), (3, "★★★☆☆ (3/5)"),
        (4, "★★★★☆ (4/5)"), (5, "★★★★★ (5/5)")
    )

    customer_info = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,  null=True, blank=True)
    default_product = models.CharField(max_length=1000, null=True, blank=True)
    rating = models.IntegerField(choices=RATING_TYPES, null=True, blank=True)
    review = models.TextField()
    date_added = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date_added"]

    def __str__(self):
        return f'{self.customer_info.username} comment'


class Payment(models.Model):
    amount = models.IntegerField()
    ref = models.CharField(max_length=200)
    email = models.EmailField()
    verified = models.BooleanField()
    date_posted = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date_posted"]

    def __str__(self):
        return f"Payment: {self.amount}"

    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref
        super().save(*args, **kwargs)

    def amount_value(self):
        return self.amount * 100

    def verify_payment(self):
        paystack = Paystack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            if result["amount"] / 100 == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False


class Visitor(models.Model):
    ip_address = models.GenericIPAddressField(unique=True)
    city = models.CharField(max_length=100, null=True)
    region = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    timezone = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

market/forms.py
from django import forms
from .models import *
from djrichtextfield.widgets import RichTextWidget
from ckeditor.fields import RichTextFormField
from django.forms import ModelForm, inlineformset_factory


class ProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Product Name',
        'type': 'text',
        'name': 'product_name',
        'id': 'product_name',
        'class': 'form-control'
    }
    )
    )
    price = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder': 'Product Price',
        'type': 'number',
        'name': 'price',
        'id': 'product_price',
        'class': 'form-control',
        'step': "0.01"
    }
    )
    )
    description = RichTextFormField(widget=forms.Textarea(attrs={
        'placeholder': 'Product Description',
        'type': 'text',
        'name': 'product_description',
        'id': 'product_description',
        'class': 'form-control'
    }
    )
    )
    delivery_period = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder': 'Product delivery period',
        'type': 'number',
        'name': 'delivery_period',
        'id': 'delivery_period',
        'class': 'form-control'
    }
    )
    )

    # category_type = Category.objects.all().values_list("id", "name")
    # category = forms.CharField(widget=forms.Select(choices=[item for item in category_type], attrs={
    #     'class': 'form-control',
    #     'name': 'category',
    #
    # }))

    class Meta:
        model = Product
        fields = ["name", "price", "category", "description", "delivery_period"]


class CategoryField(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["category"]


class ImageField(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={
        "name": "images",
        "required": True,
        "multiple": True,
        "type": "file",
        "accept": "image/*"
    }
    )
    )

    class Meta:
        model = ProductImage
        fields = ["image"]


ImageFormSet = inlineformset_factory(
    Product, ProductImage, fields=['image'],
    extra=1, can_delete=True, can_delete_extra=True
)


class ReviewBox(forms.ModelForm):
    RATING_TYPES = (
        (1, "★☆☆☆☆ (1/5)"), (2, "★★☆☆☆ (2/5)"), (3, "★★★☆☆ (3/5)"),
        (4, "★★★★☆ (4/5)"), (5, "★★★★★ (5/5)")
    )

    rating = forms.CharField(widget=forms.Select(choices=RATING_TYPES, attrs={
        'class': 'form-control',
        'name': 'education',

    }))

    review = forms.CharField(widget=forms.Textarea(attrs={
        "name": "product review",
        "placeholder": "Product Review?",
        'type': 'text',
        "rows": 3,
        "required": True
    }))

    class Meta:
        model = ProductReview
        fields = ["rating", "review"]

market/templates/market/test.html
{% extends "admin/base_site.html" %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <h3 style="font-size:22px">Are you sure?</h3>
    <p>
        Are you sure you want to apply 10% discount on the selected items?
    </p>
    <ul>
        {% for order in orders %}
        <li>
            {{ order }}
        </li>
        <input type="hidden" name="_selected_action" value="{{ order.pk }}"/>
        {% endfor %}
    </ul>
    <input type="hidden" name="action" value="apply_discount"/>
    <input type="submit" name="apply" value="Apply discount"/>
</form>
{% endblock %}

market/templates/market/update_product.html
{% extends 'market/base.html' %}
{% block title %}Market{% endblock %}
{% load static %}
{% load filtertags %}
{% load crispy_forms_tags %}
{% block content %}
<style>
   .section {
      background: #fd5631;
      border-color: #fd5631;
      color: #fff;
      position: relative;

   }
   .search-category {
        position: absolute;
        top: 200px;
        width: 84%;
        background-color: #fff;
   }
</style>
<div class="section">
    <div class="container py-5 mt-1">
        <h3><b>Update {{product}}</b></h3>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <b>{{ field }}</b>: {{ error }}
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}
        {% if formset.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in formset.errors.items %}
            {% for error in errors %}
            <b>{{ field }}</b>: {{ error }}
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}

        {{ formset.management_form }}
        {{ formset.non_form_errors }}
    </div>
</div>
<br><br>
<div class="container mb-5">
    <div class="row mb-5">
        <div class="col-lg-9">
            <form enctype="multipart/form-data" method="post" id="product_form">
                {% csrf_token %}
                <!-- main form start --- in our case product form -->
                <div class="form-group">
                    <label>Product name*</label>
                    {{ form.name }}
                    <div class="form-row mt-3">
                        <div class="col-md-6 mb-3">
                            {{ category_field|crispy }}
                            <!--                        <label>Category</label>-->
                            <!--                        {{ form.category }}-->
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>Price*</label>
                            {{ form.price }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Description*</label>
                        {{ form.description }}
                        {{ form.media }}
                    </div>
                    <div class="form-group">
                        <label>Delivery period*</label>
                        {{ form.delivery_period }}
                    </div>

                    {% if form.help_text %}
                    <small style="color: grey">{{ form.help_text }}</small>
                    {% endif %}
                    {% for error in form.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- main form end --- in our case product form -->

                <!-- inline form for Images start -->

                <!-- EXPLAINING with named_formsets.images as formset -->
                <!-- Note: named_formsets is used in get_context_data function in views.py -->
                <!-- Note: here images is our ImageFormSet name, used in get_named_formsets function in views.py -->
                {% with named_formsets.images as formset %}
                {{ formset.management_form }}
                <script type="text/html" id="images-template">   // id="inlineformsetname-template"
                <tr id="images-__prefix__" class=hide_all> // id="inlineformsetname-__prefix__"
                    {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                    {% endfor %}

                    {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                    {% endfor %}
                </tr>
                </script>
                <br>
                <div id="wrapper">
                    <div class="card-header">
                        <h4 class="card-title">Update Images</h4>
                    </div>
                    <div align="center">
                        <br>
                        <table class="table card-body">
                            <thead class="text-secondary">
                            <td>Image<span style="color: black;" class="required">*</span></td>
                            <td>Delete?</td>
<!--                            <th>Custom Delete btn</th>-->
                            </thead>
                            <tbody id="item-images">  <!-- id="item-inlineformsetname" -->
                            <!-- formset non forms errors -->
                            {% for error in formset.non_form_errors %}
                            <span style="color: red">{{ error }}</span>
                            {% endfor %}
                            {% for formss in formset %}
                            {{ formss.management_form }}
                            <tr id="images-{{ forloop.counter0 }}" class=hide_all>
                                <!-- id="inlineformsetname-counter" -->
                                {{ formss.id }}
                                {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                    <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </td>
                                {% endfor %}
                                <!-- delete code -->
<!--                                {% if formss.instance.pk %}-->
<!--                                <td>-->
<!--                                    <button type="button" class="btn btn-danger" data-toggle="modal"-->
<!--                                            data-target="#exampleModal{{formss.instance.pk}}">-->
<!--                                        Delete-->
<!--                                    </button>-->
<!--                                    &lt;!&ndash; Modal &ndash;&gt;-->
<!--                                </td>-->
<!--                                {% endif %}-->
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <a href="#" id="add-image-button" class="btn btn-secondary add-images">Add More</a>
                        <!-- id="add-inlineformsetname-button" -->
                    </div>
                </div>
                {% endwith %}
                <!-- inline form for Images end -->
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-secondary btn-block">Submit</button>
                </div>
            </form>

            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                    crossorigin="anonymous"></script>

            <script>
                $(document).ready(function() {
                    // when user clicks add more btn of images
                  $('.add-images').click(function(ev) {
                      ev.preventDefault();
                      var count = $('#item-images').children().length;
                      var tmplMarkup = $('#images-template').html();
                      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
                      $('#item-images').append(compiledTmpl);

                      // update form count
                      $('#id_images-TOTAL_FORMS').attr('value', count+1);
                  });
              });

            </script>
        </div>
        <br>
        <br>
        <br>
        <br>

        <div class="col-lg-3 col-md-3 col-sm-3 col-6">
            <br><br><br>
            <div class="sticky-top" style="top: 39px">
                <h5 class="mb-4"><b>Preview</b></h5>

                <a href="{{ product.get_absolute_url }}">
                    {% if product.productimage_set.all %}

                    {% for product_image in product.productimage_set.all %}
                    {% if forloop.first %}

                    <div class="single-testimonial text-center">
                        <img src="{{ product_image.image.url }}" fill="777" background="#777" color="#777" alt=""
                             class="thumbnail-product">
                    </div>
                    {% endif %}

                    {% endfor %}

                    {% else %}
                    <img src="{{ product.image.url }}" fill="777" background="#777" color="#777" alt=""
                         class="thumbnail-product">
                    {% endif %}
                    <style>
                        .thumbnail-product{
                            width: 100%;
                            height: 200px;
                            box-shadow:hsl(0, 0%, 80%) 0 0 16px;
                            transition: .3s
                        }
                        .col-lg-4{transition: .3s}
                        .col-lg-4:hover{
                            width: 100%;
                            height: 200px;
                            transform: translateY(-6px);
                            box-shadow:hsl(0, 0%, 80%) 0 0 16px;
                        }
                        .tox-notification{display: none !important;}




                    </style>
                </a>

                <div class="card p-2 shadow">
                    <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                        <p class="text-secondary mb-1">by <a href="{% url 'vendor' product.vendor %}">
                            {{ product.vendor }}</a> in
                            <a href="/market/?category_id={{ product.category.id }}">
                                {{ product.category }}
                            </a>
                        </p>
                        <h6 class="mb-3 mt-2 text-truncate">{{ product.name }}</h6>
                        <p class="fs--1">
                            {% for i in product.rating_count|times %}
                            <span class="fa fa-star checked text-warning"></span>
                            {% endfor %}
                            {% for i in product.rating_count|times_minus %}
                            <span class="fa fa-star"></span>
                            {% endfor %}
                            <span class="text-500 text-grey fw-semi-bold ms-1">
                                ({{product.productreview_set.count}} people rated)</span>
                        </p>
                        <style>
                            .fw-semi-bold {
                                font-weight: 500 !important;
                                color: grey !important;
                            }




                        </style>
                        <div class="media">
                            <div class="d-block">
                                <img src="{% static 'images/cart.png' %}" width="23px" height="23px" alt="">
                                <!--                                <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-download"-->
                                <!--                                     fill="currentColor"-->
                                <!--                                     xmlns="http://www.w3.org/2000/svg">-->
                                <!--                                    <path fill-rule="evenodd"-->
                                <!--                                          d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>-->
                                <!--                                    <path fill-rule="evenodd"-->
                                <!--                                          d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>-->
                                <!--                                </svg>-->
                                <strong class="ml-0"> {{ product.product_purchase }} </strong> sales
                            </div>
                            <div class="media-body">
                                <div class="d-flex float-right badge badge-warning alert alert-warning py-1">
                                    <h6><b>₦{{ product.price|floatformat:2 }}</b></h6>
                                </div>
                            </div>
                        </div>

                    </a>

                </div>
            </div>
        </div>

    </div>
</div>
<style>
    #wrapper {
        border: 1px solid #000;
        border-radius: 15px;
        padding-bottom: 20px;
    }
</style>
{% endblock %}